
*** CORRELATIONS BETWEEN THE OBSERVED AND THE PREDECTED VALUES IN THE VALIDATION SAMPLE***


CORRELATIONS
  /VARIABLES=SEL_VALID_O SEL_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SEV_VALID_O SEV_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IDENTITY_VALID_O IDENTITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFDIR_VALID_O SELFDIR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMPATHY_VALID_O EMPATHY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INTIMACY_VALID_O INTIMACY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUICIDE_VALID_O SUICIDE_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AMBIG_VALID_O AMBIG_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EGODYST_VALID_O EGODYST_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IQ_VALID_O IQ_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFESTEEM_VALID_O SELFESTEEM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HOPE_VALID_O HOPE_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFAFFICACY_VALID_O SELFAFFICACY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WELLBEING_VALID_O WELLBEING_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ADAPT_VALID_O ADAPT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RESILI_VALID_O RESILI_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=LEAD_VALID_O LEAD_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOC_SK_VALID_O SOC_SK_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACT_DAIL_VALID_O ACT_DAIL_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=FUN_COM_VALID_O FUN_COM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACUTE_VALID_O ACUTE_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CHRONIC_VALID_O CHRONIC_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=TRAUMA_PAST_VALID_O TRAUMA_PAST_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=TRAUMA_PRESENT_VALID_O TRAUMA_PRESENT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEPR_VALID_O DEPR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MANIA_VALID_O MANIA_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOMAT_VALID_O SOMAT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANXIE_VALID_O ANXIE_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AUTISM_VALID_O AUTISM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEV_SOC_DIS_VALID_O DEV_SOC_DIS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WITHD_VALID_O WITHD_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATYPI_VALID_O ATYPI_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATTE_PR_VALID_O ATTE_PR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HYPER_VALID_O HYPER_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AGGR_VALID_O AGGR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=COND_PR_VALID_O COND_PR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=BULLY_VALID_O BULLY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANG_CONT_VALID_O ANG_CONT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=NEG_EMOT_VALID_O NEG_EMOT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMOT_SELF_C_VALID_O EMOT_SELF_C_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EXE_FUN_VALID_O EXE_FUN_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMOTIONAL_LABILITY_VALID_O EMOTIONAL_LABILITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANXIOUSNESS_VALID_O ANXIOUSNESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SEPARATION_INSECURITY_VALID_O SEPARATION_INSECURITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PERSEVERATION_VALID_O PERSEVERATION_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RESTRICTED_AFFECTIVITY_VALID_O RESTRICTED_AFFECTIVITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUBMISSIVENESS_VALID_O SUBMISSIVENESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WITHDRAWAL_VALID_O WITHDRAWAL_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANHEDONIA_VALID_O ANHEDONIA_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEPRESSIVITY_VALID_O DEPRESSIVITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INTIMACY_AVOIDANCE_VALID_O INTIMACY_AVOIDANCE_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUSPICIOUSNESS_VALID_O SUSPICIOUSNESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MANIPULATIVENESS_VALID_O MANIPULATIVENESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DECEITFULNESS_VALID_O DECEITFULNESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=GRANDIOSITY_VALID_O GRANDIOSITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATTENTION_SEEKING_VALID_O ATTENTION_SEEKING_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CALLOUSNESS_VALID_O CALLOUSNESS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HOSTILITY_VALID_O HOSTILITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IMPULSIVITY_VALID_O IMPULSIVITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DISTRACTIBILITY_VALID_O DISTRACTIBILITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RIGID_PERFECTIONISM_VALID_O RIGID_PERFECTIONISM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IRRESPONSIBILITY_VALID_O IRRESPONSIBILITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RISK_TAKING_VALID_O RISK_TAKING_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ECCENTRICITY_VALID_O ECCENTRICITY_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PERCEPTUAL_DYSREGULATION_VALID_O PERCEPTUAL_DYSREGULATION_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UNUSUAL_BELIEFS_VALID_O UNUSUAL_BELIEFS_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACT_VALID_O ACT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DSP_VALID_O DSP_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PAG_VALID_O PAG_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PRO_VALID_O PRO_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SPL_VALID_O SPL_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WDR_VALID_O WDR_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CONV_VALID_O CONV_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DSC_VALID_O DSC_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=FAN_VALID_O FAN_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=OMN_VALID_O OMN_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=REP_VALID_O REP_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOM_VALID_O SOM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ISO_VALID_O ISO_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UND_VALID_O UND_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ALT_VALID_O ALT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HUM_VALID_O HUM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IDL_VALID_O IDL_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RFM_VALID_O RFM_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DN_VALID_O DN_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUB_VALID_O SUB_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INT_VALID_O INT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUP_VALID_O SUP_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANT_VALID_O ANT_VALID_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.




