
*** CORRELATIONS BETWEEN THE OBSERVED AND THE PREDECTED VALUES IN THE TESTING SAMPLE***


CORRELATIONS
  /VARIABLES=SEL_TEST_O SEL_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SEV_TEST_O SEV_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IDENTITY_TEST_O IDENTITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFDIR_TEST_O SELFDIR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMPATHY_TEST_O EMPATHY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INTIMACY_TEST_O INTIMACY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUICIDE_TEST_O SUICIDE_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AMBIG_TEST_O AMBIG_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EGODYST_TEST_O EGODYST_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IQ_TEST_O IQ_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFESTEEM_TEST_O SELFESTEEM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HOPE_TEST_O HOPE_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SELFAFFICACY_TEST_O SELFAFFICACY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WELLBEING_TEST_O WELLBEING_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ADAPT_TEST_O ADAPT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RESILI_TEST_O RESILI_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=LEAD_TEST_O LEAD_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOC_SK_TEST_O SOC_SK_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACT_DAIL_TEST_O ACT_DAIL_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=FUN_COM_TEST_O FUN_COM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACUTE_TEST_O ACUTE_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CHRONIC_TEST_O CHRONIC_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=TRAUMA_PAST_TEST_O TRAUMA_PAST_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=TRAUMA_PRESENT_TEST_O TRAUMA_PRESENT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEPR_TEST_O DEPR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MANIA_TEST_O MANIA_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOMAT_TEST_O SOMAT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANXIE_TEST_O ANXIE_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AUTISM_TEST_O AUTISM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEV_SOC_DIS_TEST_O DEV_SOC_DIS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WITHD_TEST_O WITHD_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATYPI_TEST_O ATYPI_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATTE_PR_TEST_O ATTE_PR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HYPER_TEST_O HYPER_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=AGGR_TEST_O AGGR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=COND_PR_TEST_O COND_PR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=BULLY_TEST_O BULLY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANG_CONT_TEST_O ANG_CONT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=NEG_EMOT_TEST_O NEG_EMOT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMOT_SELF_C_TEST_O EMOT_SELF_C_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EXE_FUN_TEST_O EXE_FUN_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=EMOTIONAL_LABILITY_TEST_O EMOTIONAL_LABILITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANXIOUSNESS_TEST_O ANXIOUSNESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SEPARATION_INSECURITY_TEST_O SEPARATION_INSECURITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PERSEVERATION_TEST_O PERSEVERATION_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RESTRICTED_AFFECTIVITY_TEST_O RESTRICTED_AFFECTIVITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUBMISSIVENESS_TEST_O SUBMISSIVENESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WITHDRAWAL_TEST_O WITHDRAWAL_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANHEDONIA_TEST_O ANHEDONIA_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DEPRESSIVITY_TEST_O DEPRESSIVITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INTIMACY_AVOIDANCE_TEST_O INTIMACY_AVOIDANCE_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUSPICIOUSNESS_TEST_O SUSPICIOUSNESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=MANIPULATIVENESS_TEST_O MANIPULATIVENESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DECEITFULNESS_TEST_O DECEITFULNESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=GRANDIOSITY_TEST_O GRANDIOSITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ATTENTION_SEEKING_TEST_O ATTENTION_SEEKING_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CALLOUSNESS_TEST_O CALLOUSNESS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HOSTILITY_TEST_O HOSTILITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IMPULSIVITY_TEST_O IMPULSIVITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DISTRACTIBILITY_TEST_O DISTRACTIBILITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RIGID_PERFECTIONISM_TEST_O RIGID_PERFECTIONISM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IRRESPONSIBILITY_TEST_O IRRESPONSIBILITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RISK_TAKING_TEST_O RISK_TAKING_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ECCENTRICITY_TEST_O ECCENTRICITY_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PERCEPTUAL_DYSREGULATION_TEST_O PERCEPTUAL_DYSREGULATION_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UNUSUAL_BELIEFS_TEST_O UNUSUAL_BELIEFS_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ACT_TEST_O ACT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DSP_TEST_O DSP_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PAG_TEST_O PAG_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=PRO_TEST_O PRO_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SPL_TEST_O SPL_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=WDR_TEST_O WDR_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=CONV_TEST_O CONV_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DSC_TEST_O DSC_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=FAN_TEST_O FAN_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=OMN_TEST_O OMN_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=REP_TEST_O REP_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SOM_TEST_O SOM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ISO_TEST_O ISO_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UND_TEST_O UND_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ALT_TEST_O ALT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HUM_TEST_O HUM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=IDL_TEST_O IDL_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=RFM_TEST_O RFM_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=DN_TEST_O DN_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUB_TEST_O SUB_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=INT_TEST_O INT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=SUP_TEST_O SUP_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=ANT_TEST_O ANT_TEST_P
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.




